### ISSUE TITLE
disable formula calculation possible?

### ISSUE THREAD

**Issue by rebootl** [dilshod/xlsx2csv#193]
Hello, this is more a question than a bugreport. Is there a simple way to disable evaluation of the formulas for the conversion. I would need to have the formula as such, e.g. =TODAY().
I tried to have a quick look at the code but I don't see where the formulas are evaluated, or how that works...
Thanks!

**Comment by ckujau** [comment]
Interesting problem, but I doubt that this will be possible without changes to the code.

There is the `--ignore-formats` switch to disable the *formatting* of cells. So, when converting a table with a `=TODAY()` field:

```
$ xlsx2csv --ignore-formats 'date' -e file.xlsx file.csv
$ A,B,C,today
one,two,three,43985
```

This `43985` appears to mean "day 43985 since the beginning of time", and since Excel [uses](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system "Differences between the 1900 and the 1904 date system in Excel") *January 1, 1900* as its [epoch date](https://en.wikipedia.org/wiki/Epoch_(computing)), this number translates (roughly) to "today" (2020-06-03):

```
$ date -d "43985 days ago"
Sat Dec 30 10:34:05 PST 1899
```

Back to the problem at hand, looking closer into the `.xlsx` file we can see:

```
$ unzip file.xlsx
$ grep -hri today . | xmllint --format --recover - | grep -C2 43985
      <c r="D2" s="1" t="n">
        <f aca="true">TODAY()</f>
        <v>43985</v>
      </c>
    </row>
```

So, this number is stored inbetween `<v> ... </v>` tags, exactly the place where `xlsx2csv.py` is [looking](https://github.com/dilshod/xlsx2csv/blob/master/xlsx2csv.py#L338). So, for that to work `xlsx2csv.py` would need a switch to look for values in `<f> ... </f>` instead, I guess?

**Comment by rebootl** [comment]
ooh, thanks for your quick reply, I'll have a look at that. I might get something to work with that input. I didn't even know I had to unzip the xlsx. :D

> An easier (and interim) solution would be to disable formulas in Excel or enclose the =today() in quotes, save the document and run xlsx2csv.py again.

We need it for a batch convert/import of hundreds of files. That's why I don't wanna/can't do it manually. :see_no_evil:
